version: '3.7'
services:
  wiki-52poke:
    container_name: wiki-52poke
    build:
      context: .
    volumes:
      - ../:/home/52poke/wiki:z
      - ../docker/nginx.conf:/etc/nginx/nginx.conf:z
      - ../docker/php.ini:/usr/local/etc/php/php.ini:z
      - ../docker/supervisord.conf:/etc/supervisor/supervisord.conf:z
    ports:
      - 8227:80
    networks:
      - isolated_nw
    restart: always
  poolcounter:
    container_name: poolcounter
    image: ghcr.io/mudkipme/poolcounter:latest
    command: -l 0.0.0.0
    ports:
      - 7531:7531
    networks:
      - isolated_nw
    restart: always

networks:
  isolated_nw:
    external: true
