composer:
	docker run --rm -v ${PWD}/../:/home/52poke/wiki:z composer:2 sh -c "cd /home/52poke/wiki && composer update --no-dev --ignore-platform-req=ext-calendar --ignore-platform-req=ext-intl --with-all-dependencies"
